### ISSUE TITLE
Update process and documentation

### ISSUE THREAD

**Issue by Compton-NIST** [usnistgov/OSCAL-DEFINE#31]
### Problem Statement

Based on recent spiral completion, it's time to update documentation around the process and produce a diagram of the workflow so that others can follow.  This will help others participate in the process, and help aid in decision-making when spirals end.

I would also like to compare this to https://sprint.usds.gov/ to see if we should make some adjustments to how we conduct spirals/efforts.

Mainly a todo for @Compton-NIST at this point.

**Comment by Compton-NIST** [comment]
Need:

- [ ] Word document for spiral template
- [ ] Use word template to record your "Spiral" feedback from your test
- [ ] Add  step by step somewhere, maybe another doc?
- [ ] Drop files in this issue

**Comment by nbg84** [comment]
[OSCAL DEFINE SPIRAL TEMPLATE_v3.docx](https://github.com/usnistgov/OSCAL-DEFINE/files/12352302/OSCAL.DEFINE.SPIRAL.TEMPLATE_v3.docx)

**Comment by Compton-NIST** [comment]
Let's hold on the word template for a few weeks.  A new spiral template was created that allows GitHub users to [fill out a template](https://github.com/usnistgov/OSCAL-DEFINE/issues/new/choose) that will create an issue with the spiral content, and is based on @nbg84's feedback.  This can eventually be moved into a markdown file that is committed in final form -- it might be automatable to commit when the issue is closed.  That would be a future implementation.  Let's see if the issue template helps.  Once we are happy with the new template, we can move into the document template.
