### ISSUE TITLE
Feedback and notes on research process as applied to the current effort/spirals.

### ISSUE THREAD

**Issue by Compton-NIST** [usnistgov/OSCAL-DEFINE#9]
A holding place for potential changes to the documentation and process as we encounter issues.

**Comment by Compton-NIST** [comment]
Not sure if we need the spiral level issues, as long as a pull request is initiated as WIP/DRAFT for the spiral, the work will be visible in the effort level issue if properly referenced.  The only drawback is that tickets will be long-running for the duration of an issue.

**Comment by iMichaela** [comment]
@Compton-NIST - I see your point, and I find it valuable. I wonder though, if more than one person works on a spiral, how do you think an activities/research-subtopic/idea should be tracked and shared with other collaborators if an issue is not created?

**Comment by Compton-NIST** [comment]
> @Compton-NIST - I see your point, and I find it valuable. I wonder though, if more than one person works on a spiral, how do you think an activities/research-subtopic/idea should be tracked and shared with other collaborators if an issue is not created?

On second thought, it does appear that the spiral issue will be useful, particularly on collecting feedback.
